### ISSUE TITLE
cifre

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/cifre#1]
![es2_30](https://cloud.githubusercontent.com/assets/3002194/13374133/194c55fe-dd7c-11e5-8e25-f335be5b1782.jpg)

**Comment by Teodoro777** [comment]
La soluzione è un pò particolare ma credo sia valida

2016-02-27 18:01 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
in attesa della nuova versione

**Comment by Teodoro777** [comment]
Aspettate, facendo 2048 ho dimenticato in che modo migliorare.. Non posso
usare i cicli, ma cosa devo fare di preciso?

Il venerdì 4 marzo 2016, Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
usare solo divisioni e modulo 10

**Comment by Teodoro777** [comment]
Eh ma che devo modificare di preciso?

Il venerdì 4 marzo 2016, Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
non devi usare 100, 1000, ecc ecc, solo 10

**Comment by Teodoro777** [comment]
Sto provando ma non capisco come sostituire 10000 con 10..

2016-03-04 21:04 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by Teodoro777** [comment]
Finalmente ho fatto

Il giorno 4 marzo 2016 22:19, Teodoro Coluccio <teodoro.coluccio@gmail.com>
ha scritto:
